builds:
  - main: ./cmd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}--{{.Arch}}"
