# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            go test -v ./... --timeout 45m
          no_output_timeout: 45m
  release:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
