# .circleci/config.yml
version: 2.1

orbs:
  windows: circleci/windows@2.4.1

workflows:
  main:
    jobs:
      - test
      - test-windows
      - test-mac
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  test:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mkdir -p /tmp/logs
            go test -v ./... --timeout 5m | tee /tmp/logs/test.log
          # Tolerate a 4 minute window of no output
          no_output_timeout: 240s
      - store_artifacts:
          path: /tmp/logs 
      - store_test_results: 
          path: /tmp/logs 
  test-windows:
    executor:
      name: windows/default
    steps:
      - checkout
      - attach_workspace:
          at: script
      - run: go test -v ./...
  
  test-mac:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: brew install go@1.17
      - run: 
          name: run tests
          command: |
            mkdir -p /tmp/logs
            # Make Go available in the PATH upon first being installed
            echo 'export PATH="/usr/local/opt/go@1.17/bin:$PATH"' >> /Users/distiller/.bash_profile
            go test -v ./... --timeout 5m | tee /tmp/logs/test.log
  release:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
